apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-schema
data:
  schema.sql: |
    CREATE TABLE IF NOT EXISTS url_map(
      slug VARCHAR(10) UNIQUE NOT NULL,
      long_url TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: urlshortener
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: schema
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: data
          emptyDir: {}
        - name: schema
          configMap:
            name: postgres-schema
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
